### ISSUE TITLE
Bot should send to chat scheduled vacations from Google Calendar

### ISSUE THREAD

**Issue by Maay** [dialogs/dialog-office-bot#5]
We are the team of corporate messenger dialog. We have Java/Python/JavaScript Bot SDK to create bots in our messenger. Since it is new, we want to develop several bots with the help of the community for everyday use.

The documentation of our Java Bot SDK is here: https://docs.dlg.im/bots/java-bot.html

The documentation of our Python Bot SDK is here: https://dialogs.github.io/python-bot-sdk/ ⁣ ⁣ ⁣

The documentation of our JavaScript Bot SDK is here: https://dialogs.github.io/js-bot-sdk/

We'd prefer to use Python or JS SDK.

Our messenger has a test instance. Web client that you should use for the development is available here: https://grpc-test.transmit.im/

For web use this endpoint: https://grpc-test.transmit.im:8443
For bots use grpc endpoint: https://grpc-test.transmit.im:9443
Test accounts:
`alice` / `password`
After you've logged in you should write to `Security Bot` user (you can find him in the search field) and write command `/bot new bot_username bot_name` where `bot_username` is the username you can choose for your new bot and `bot_name` is his display name

We've open-sourced several bots that you can look up to for examples https://github.com/dialogs?utf8=%E2%9C%93&q=-bot&type=&language=

Please feel free to ask questions in our community https://dlg.im/@botsfordialog ⁣ ⁣

*Bot should send to chat scheduled vacations from Google Calendar*

"1) Bot config should be managed from a text config file. In the config file, we specify data for integration with GSuite. The login in GSuite and dialog is the same.
2) The user writes the bot command `Holidays Calendar`. The command should be configurable in config-file.
3) The bot sends the user a text with a list of the titles and their dates of all the events in the calendar. Each event on a separate line. From the closest to the farthest by date. The calendar should be configurable in config-file.
4) The user writes a bot command `Holidays per MONTH`. `MONTH` is a name of a month.
5) The bot sends the user a text with the list of the titles and dates of all the events in the calendar for the specified month. Each event on a separate line. From the closest to the farthest.
6) The user writes the bot command `Holidays in QX` where X is the number of the quarter. 1 - January, February, March; 2 - April, May, June; 3 - July, August, September; 4 - October, November, December.
7) The bot sends the user a text of the list of titles of all events and its dates in the calendar for the specified quarter. Each event on a separate line. From the closest to the farthest.

This is one of the features that this bot has. Look up other issues in this repo for other features. Each feature can be developed in separate bots (even in different languages but with the same name) using the same token. But, in case of a private chat with a bot, you have to add a check that peer id is equal to sender id in incoming SeqUpdate params. It’s needed to prevent the feature’s mutual influence. For example(Python):

```
def on_msg1(*params):
    if params[0].peer.id == params[0].sender_uid:  # this prevents false reactions 
        bot1.messaging.send_message(
            …
        )
```

For bounty to be verified, it’s necessary to create documentation for it.

**Comment by ShellAddicted** [comment]
my solution #6 is ready, waiting for review.

**Comment by Drymonade** [comment]
@ShellAddicted There are some troubles: 
```
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
```
Bot is ready, but doesn't print anything about calendar id and etc. Are you sure requirements.txt is completed enough?

**Comment by ShellAddicted** [comment]
@Drymonade
those exceptions are out of my control and are part of legacy code in googleapiclient which handles them itself. as far I can tell, they can be safely ignored.
I've just tested the bot and it works, I can confirm that `requirements.txt` is completed enough (`dialog_bot_sdk` is missing but you already have that)

have you enabled `show_calendars` in settings.json?

**Comment by Drymonade** [comment]
@ShellAddicted 
> those exceptions are out of my control and are part of legacy code in googleapiclient which handles them itself. as far I can tell, they can be safely ignored.

Do you have the same output when bot starts?

**Comment by ShellAddicted** [comment]
this is a cold start (no pickle file)
(I click on the link and login with my personal google account)*
```
@Drymonade 
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?rXXXXX-

"GET /?state=XXXX&scope=https://www.googleapis.com/auth/calendar.readonly HTTP/1.1" 200 65
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/shelladdicted/IDE/dialog-office-bot/venx/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shelladdicted/IDE/dialog-office-bot/venx/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shelladdicted/IDE/dialog-office-bot/venx/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shelladdicted/IDE/dialog-office-bot/venx/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/shelladdicted/IDE/dialog-office-bot/venx/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest
URL being requested: GET https://www.googleapis.com/calendar/v3/users/me/calendarList?alt=json
XXXX@group.calendar.google.com => WSBK 2019 all events
XXX@gmail.com => XXX@gmail.com
XXX@group.calendar.google.com => My Calendar Name
XXX.calendar.google.com => MotoGP 2019 All Events
Bot is ready.
```

**Comment by Drymonade** [comment]
@ShellAddicted 
That's OK, just for check. 
Please, can you remove `user_id` field from settings? It's the bot not only for one user.

**Comment by ShellAddicted** [comment]
@Drymonade 
1 calendar -> multiple bot users?

**Comment by Drymonade** [comment]
@ShellAddicted Yes, it's a corporate calendar with common holidays, we need only one general Google account with one calendar for bot and multiple access to bot.

**Comment by ShellAddicted** [comment]
@Drymonade check https://github.com/dialogs/dialog-office-bot/pull/6/commits/7bf035dc057fc82cff73963243aa43332905cb58 
set `user_id` to `null` to open it to anyone (not recommended)
or set `user_id` to a list of int containing user_id of allowed users

do you like this solution or should I just remove the option?

**Comment by Drymonade** [comment]
@ShellAddicted Yeah, that's cool! Will test it soon.

**Comment by Drymonade** [comment]
@ShellAddicted 
There are some other troubles with calendar (first line is printed `evt`):
```
{'kind': 'calendar#event', 'etag': '"3101527224000000"', 'id': '20190501_60o30dj368o30c1g60o30dr56c', 'status': 'confirmed', 'htmlLink': 'https://www.google.com/calendar/event?eid=MjAxOTA1MDFfNjBvMzBkajM2OG8zMGMxZzYwbzMwZHI1NmMgcnUucnVzc2lhbiNob2xpZGF5QHY', 'created': '2019-02-21T15:40:12.000Z', 'updated': '2019-02-21T15:40:12.000Z', 'summary': 'Праздник Весны и Труда', 'creator': {'email': 'ru.russian#holiday@group.v.calendar.google.com', 'displayName': 'Праздники РФ', 'self': True}, 'organizer': {'email': 'ru.russian#holiday@group.v.calendar.google.com', 'displayName': 'Праздники РФ', 'self': True}, 'start': {'date': '2019-05-01'}, 'end': {'date': '2019-05-02'}, 'transparency': 'transparent', 'visibility': 'public', 'iCalUID': '20190501_60o30dj368o30c1g60o30dr56c@google.com', 'sequence': 0}
Exception
Traceback (most recent call last):
  File "main.py", line 84, in on_msg
    r = get_event_list(SETTINGS["calendar_id"], start=now, event_limit=SETTINGS["num_events_limit"])
  File "main.py", line 60, in get_event_list
    event_start = datetime.datetime.fromisoformat(evt["start"]["dateTime"])
KeyError: 'dateTime'
```
I see that some fields (`dateTime`, `description`) are not present in our version of calendar. Can you integrate with our particular calendar `ru.russian#holiday@group.v.calendar.google.com`?

**Comment by ShellAddicted** [comment]
@Drymonade 
fixed (https://github.com/dialogs/dialog-office-bot/pull/6/commits/9643788982bf0563d9789a03893d16000f1bd53c)

**Comment by Maay** [comment]
@ShellAddicted please check this bounty as solved on bountysource
